# Generated by Django 5.2.6 on 2025-09-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(default='', help_text='Answer in English'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_hi',
            field=models.TextField(default='', help_text='Answer in Hindi'),
        ),
    ]
