# Generated by Django 5.2.6 on 2025-10-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_faq_answer_faq_answer_en_faq_answer_hi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='User utterance')),
                ('intent', models.CharField(help_text='Intent label', max_length=100)),
            ],
        ),
    ]
