# Generated by Django 5.2.6 on 2025-10-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_trainingexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(default='general', help_text="Category like 'general', 'auto_insurance'", max_length=50),
        ),
    ]
